### ISSUE TITLE
Expo: MaterialIcons is not a system font error.

### ISSUE THREAD

**Issue by Alderr** [satya164/PocketGear#17]
I am using Expo on my HTC Desire 530 to test it. The error mentioned in title does not show when I run it from the Expo display, it happens when I run it from my machine(npm start -> server launches -> takes picture of QR Code). 

Disclaimer: First time ever really using any of these libraries/tech/etc so Im going to show every single step I've done that brought me to the error.

[1]  Cloned repo, npm install, yarn. Nothing wrong so far.

[2] I run "npm start" and this error pops up. 

![errorbabelenv](https://user-images.githubusercontent.com/1088165/27620076-17707736-5b95-11e7-8349-32b0caf50a99.png)

[3] Googled this. [A Babel.rc guide](https://babeljs.io/docs/usage/babelrc/) So, I ended up just removing "BABEL_ENV" from npm start command in package.json and doing it in the command prompt.

![1stpackjson](https://user-images.githubusercontent.com/1088165/27620177-b51d270e-5b95-11e7-8afd-e52531dce8b6.png)
![setbabelenv](https://user-images.githubusercontent.com/1088165/27620180-bcec99ce-5b95-11e7-915e-2f95053000af.png)

[4] Packager runs, I get my QR Code and I scan it.

![qrcode](https://user-images.githubusercontent.com/1088165/27620251-4ac3ca06-5b96-11e7-9ec6-11429fd2eb4a.png)

[5] Error shows up and a lot of the icons end up missing or replaced with something else. 
![screenshot_20170628-001353](https://user-images.githubusercontent.com/1088165/27620525-4188075c-5b98-11e7-8ff3-5349a228494d.png)
![screenshot_20170628-001409](https://user-images.githubusercontent.com/1088165/27620528-433f2576-5b98-11e7-8ba4-e5efdab46cd0.png)
![screenshot_20170628-001813](https://user-images.githubusercontent.com/1088165/27620530-44d35858-5b98-11e7-9f37-4c601ad67e42.png)

**Comment by satya164** [comment]
Hmm.. That's weird. I dunno much about windows to say what's the issue. The simple workaround will be to change the preset to `expo` from `react-native` in `.babelrc`.

After changing it, make sure to run `npm start -- --reset-cache`

**Comment by Alderr** [comment]
Cool, it works but now haha I'm wondering why this works and how this will affect me when using react-native-vector-icons in my CRNA projects.

**Comment by satya164** [comment]
@Alderr this is a mixed vanilla + CRNA project, that's why you faced the issue. I believe no one has done it before, so don't know the proper way yet.

You won't face any such issue with normal CRNA projects.
