### ISSUE TITLE
error when typing in search bar

### ISSUE THREAD

**Issue by buncismamen** [satya164/PocketGear#19]
I open the apps from expo explore apps

when I typing in the search bar
this error happen

Uncaught Error: undefined is not a function ( evaluating 'this._root.scrollTo(e)')
value@cached-bundle-experience-%40satya164%2Fpocketgear:887
Time: 1:04:43 Fatal Error

also @satya164 did you consider implementing redux to this apps?, I think it could be a example for good practices for redux+react-navigation like [MovieApp](https://github.com/junedomingo/movieapp) to [wix/react-native-navigation](https://github.com/wix/react-native-navigation)

**Comment by satya164** [comment]
@buncismamen So I was unable to repro this on master. I probably changed something after I published. I published a new version today. Can you try and lemme know if it still happens?

Regarding Redux, I think Redux is overkill for such an app. Probably it's good example of an app where you don't need Redux :)

**Comment by buncismamen** [comment]
@satya164 the bug is gone now.
